src/wcp-web/src/main/java/com/farm/wcp/controller/AIController.java
package com.farm.wcp.controller;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import com.farm.core.auth.domain.LoginUser;
import com.farm.core.page.ViewMode;
import com.farm.core.sql.result.DataResult;
import com.farm.core.time.TimeTool;
import com.farm.doc.server.FarmDocIndexInter;
import com.farm.doc.server.FarmDocManagerInter;
import com.farm.doc.server.FarmDocTypeInter;
import com.farm.doc.util.HtmlUtils;
import com.farm.llm.utils.LlmMessage;
import com.farm.llm.utils.LlmMessage.M_TYPE;
import com.farm.parameter.FarmParameterService;
import com.farm.tex.AiQuestor;
import com.farm.tex.domainex.AiQuestorMessage;
import com.farm.tex.domainex.AiQuestorMessage.MessageState;
import com.farm.wcp.util.ImHistory;
import com.farm.wcp.util.ThemesUtil;
import com.farm.web.WebUtils;

/**
 * 智能对话服务
 * 
 * @author wangdogn
 *
 */
@RequestMapping("/aiweb")
@Controller
public class AIController extends WebUtils {

	private static final Logger log = Logger.getLogger(AIController.class);
	@Resource
	private FarmDocIndexInter farmDocIndexManagerImpl;
	@Resource
	private FarmDocTypeInter farmDocTypeManagerImpl;
	@Resource
	private FarmDocManagerInter farmDocManagerImpl;

	public static String getThemePath() {
		return FarmParameterService.getInstance().getParameter("config.sys.web.themes.path");
	}

	/**
	 * 独立的AI对话页面
	 * 
	 * @return
	 * @throws Exception
	 */
	@RequestMapping(value = "/PubAiChat", method = RequestMethod.GET)
	public ModelAndView aiChat(String docid, String actiontype, HttpSession session, HttpServletRequest request)
			throws Exception {
		try {
			return ViewMode.getInstance().returnModelAndView("web-simple/aichat/aiChat");
		} catch (Exception e) {
			return ViewMode.getInstance().setError(e.toString())
					.returnModelAndView(ThemesUtil.getThemePath() + "/error");
		}
	}

	/**
	 * 发送消息，并接收回复
	 */
	@RequestMapping("/PubSendmgs")
	@ResponseBody
	public Map<String, Object> StatCommitTestDate(String message, HttpSession session, HttpServletRequest request) {
		String backmessage = null;
		String talkSessionId = AiQuestor.getTalkSessionId(session, request);
		if (FarmParameterService.getInstance().getParameterBoolean("config.imbar.login.force")
				&& getCurrentUser(session) == null) {
			// 未登录返回必须登录提示信息
			return ViewMode.getInstance().putAttr("msg", "<div class='farm_wcp_ai_msg' >请&nbsp;<b>登录</b>&nbsp;账户</div>")
					.returnObjMode();
		}
		// 向会话缓存中添加历史记录
		ImHistory.addMessage(session, message, message, LlmMessage.M_TYPE.USER);
		// none/gpt/search
		if (FarmParameterService.getInstance().getParameter("config.imbar.type").equals("llm")) {
			if (AiQuestor.talking(talkSessionId) != null) {
				return ViewMode.getInstance()
						.putAttr("msg", AiQuestor.talking(talkSessionId).getHtml() + "<b>(当前存在未完成的会话)</b>")
						.returnObjMode();
			}
			// AI问答
			AiQuestorMessage bmessage = AiQuestor.send(message, talkSessionId, null, ImHistory.getMessages(session));
			backmessage = bmessage.getHtml();
		}

		if (backmessage == null || backmessage.indexOf("[ERROR]") == 0
				|| FarmParameterService.getInstance().getParameter("config.imbar.type").equals("search")) { // 本地查詢接口
			// search接口
			String searchRrt = null;
			try {
				DataResult result = farmDocIndexManagerImpl.search(message,
						getCurrentUser(session, request) == null ? null : getCurrentUser(session, request).getId(), 1);
				String linkKnows = getKnowLinksBySearchResult(result.getResultList());
				if (StringUtils.isNotBlank(linkKnows)) {
					searchRrt = "找到以下知识：<br/><br/>" + linkKnows;
				} else {
					searchRrt = "暂未找到相关知识";
				}
			} catch (Exception e) {
				e.printStackTrace();
			}

			if (StringUtils.isBlank(backmessage)) {
				backmessage = searchRrt;
			} else {
				backmessage = backmessage + "<br/>" + searchRrt;
			}

			AiQuestorMessage bmessage = new AiQuestorMessage(talkSessionId);
			bmessage.setMessage(backmessage);
			bmessage.submit(MessageState.COMPELET);
			ImHistory.addMessage(session, bmessage.getHtmlmsg(), HtmlUtils.HtmlRemoveTag(bmessage.getMessage()),
					LlmMessage.M_TYPE.ASSISTANT);
		}
		return ViewMode.getInstance().putAttr("msg", backmessage).returnObjMode();
	}

	/**
	 * 加载当前消息
	 */
	@RequestMapping("/PubLoadmsg")
	@ResponseBody
	public Map<String, Object> loadmsg(String ids, HttpSession session, HttpServletRequest request) {
		try {
			List<AiQuestorMessage> msgs = new ArrayList<AiQuestorMessage>();
			for (String id : parseIds(ids)) {
				AiQuestorMessage bmessage = AiQuestor.loadMessage(id);
				if (bmessage.getState().equals(MessageState.COMPELET)) {
					ImHistory.addMessage(session, bmessage.getHtmlmsg(), HtmlUtils.HtmlRemoveTag(bmessage.getMessage()),
							LlmMessage.M_TYPE.ASSISTANT);
					bmessage.submit(MessageState.EXPIRE);
				}
				msgs.add(bmessage);
			}
			return ViewMode.getInstance().putAttr("msgs", msgs).returnObjMode();
		} catch (Exception e) {
			return ViewMode.getInstance().setError(e.getMessage()).returnObjMode();
		}
	}

	/**
	 * 拼接一个供gpt参考的知识内容，从查询结果中抽取该知识
	 * 
	 * @param list
	 * @return
	 */
	private String getKnowLinksBySearchResult(List<Map<String, Object>> list) {
		String know = null;
		for (Map<String, Object> node : list) {
			String title = (String) node.get("TITLE");
			title = HtmlUtils.HtmlRemoveTag(title).replace("\"", "");
			String docdescribe = (String) node.get("DOCDESCRIBE");
			docdescribe = HtmlUtils.HtmlRemoveTag(docdescribe).replace("\"", "");
			String ID = (String) node.get("ID");
			String DOMTYPE = (String) node.get("DOMTYPE");
			String url = null;
			if (DOMTYPE.equals("file")) {
				url = "webdoc/view/PubFile" + ID + ".html";
			}
			if (DOMTYPE.equals("fqa")) {
				url = "webquest/fqa/Pub" + ID + ".html";
			}
			if (!DOMTYPE.equals("fqa") && !DOMTYPE.equals("file")) {
				url = "webdoc/view/Pub" + ID + ".html";
			}
			String a = "<a target='_blank' title='"
					+ docdescribe + "' href='" + url + "'>" + title + "</a><br/>";
			if (know == null) {
				know = a;
			} else {
				know = know + a;
			}
		}
		return know;
	}

	/**
	 * 清理历史消息
	 * 
	 * @param session
	 * @param request
	 * @return
	 */
	@RequestMapping("/PubClear")
	@ResponseBody
	public Map<String, Object> PubClear(HttpSession session, HttpServletRequest request) {
		ImHistory.clearMessage(session);
		return ViewMode.getInstance().returnObjMode();
	}

	/**
	 * 立即停止回答
	 * 
	 * @param session
	 * @param request
	 * @return
	 */
	@RequestMapping("/PubStopMsg")
	@ResponseBody
	public Map<String, Object> PubStopMsg(String ids, HttpSession session, HttpServletRequest request) {
		try {
			for (String id : parseIds(ids)) {
				AiQuestorMessage.stop(id);
			}
			return ViewMode.getInstance().returnObjMode();
		} catch (Exception e) {
			return ViewMode.getInstance().setError(e.getMessage()).returnObjMode();
		}
	}

	/**
	 * 加载历史消息
	 * 
	 * @param session
	 * @param request
	 * @return
	 */
	@RequestMapping("/PubLoadhis")
	@ResponseBody
	public Map<String, Object> PubLoadhis(HttpSession session, HttpServletRequest request) {
		List<LlmMessage> list = ImHistory.getMessages(session);
		if (list.size() <= 0) {
			String key = FarmParameterService.getInstance().getParameter("config.imbar.default.tip");
			if (!key.trim().toLowerCase().equals("none")) {
				LlmMessage message = null;
				// 获取知识库默认提示消息
				if (message == null) {
					message = new LlmMessage(key, M_TYPE.FUNCTIP);
				}
				list.add(message);
			}
		}
		return ViewMode.getInstance().putAttr("msgs", list).returnObjMode();
	}

	private LoginUser getCurrentUser(HttpSession session, final HttpServletRequest request) {
		LoginUser user = null;
		if (getCurrentUser(session) != null) {
			user = getCurrentUser(session);
		} else {
			user = new LoginUser() {

				@Override
				public String getName() {
					return null;
				}

				@Override
				public String getLoginname() {
					return null;
				}

				@Override
				public String getId() {
					return null;
				}
			};
		}
		return user;
	}
}

src/wcp-web/src/main/webapp/view/web-simple/resume/appraisal.jsp
<%@ page language="java" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib uri="/view/conf/farmtag.tld" prefix="PF"%>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<base href="<PF:basePath/>" />
<title>${USEROBJ.name}-自我评价-<PF:ParameterValue
		key="config.sys.title" /></title>
<meta name="description"
	content='<PF:ParameterValue key="config.sys.mate.description"/>'>
<meta name="keywords"
	content='<PF:ParameterValue key="config.sys.mate.keywords"/>'>
<meta name="author"
	content='<PF:ParameterValue key="config.sys.mate.author"/>'>
<meta name="robots" content="noindex,nofllow">
<jsp:include page="../atext/include-web.jsp"></jsp:include>
<script charset="utf-8"
	src="<PF:basePath/>text/lib/super-validate/validate.js"></script>
<script charset="utf-8"
	src="<PF:basePath/>text/lib/bootstrapdatepicker/bootstrap-datetimepicker.min.js"></script>
<link
	href="<PF:basePath/>text/lib/bootstrapdatepicker/bootstrap-datetimepicker.css"
	rel="stylesheet">
<link href="view/web-simple/atext/style/resume.css" rel="stylesheet">
</head>
<body>
	<jsp:include page="../commons/head.jsp"></jsp:include>`
	<jsp:include page="../commons/superContent.jsp"></jsp:include>
	<div class="containerbox">
		<div class="container ">
			<div class="row  column_box">
				<div class="col-md-12">
					<h3>${USEROBJ.name}-自我评价<a class="resum_button btn btn-info btn-sm"
							href="resume/view.do?userid=${USEROBJ.id}">返回</a>
					</h3>
				</div>
			</div>
			<div class="row ">
				<div class="widget-box shadow-box" style="min-width: 800px;">
					<div class="title">
						<h3>
							<i class="glyphicon glyphicon-star"></i>自我评价
						</h3>
					</div>
					<div class="stream-list p-stream">
						<form role="form" action="resume/appraisalCommit.do" id="SubmitFormId" method="post">
							<input type="hidden" name="id" value="${resumeappraisal.id}">
							<table class="table resum_unit" style="font-size: 12px;">
								<tr>
									<td class="resum_title">自我评价</td>
									<td>
										<textarea id="appraisalid" name="appraisal"
											style="height: 90px; width: 100%;">${resumeappraisal.appraisal}</textarea>
									</td>
								</tr>
								<tr>
									<td class="resum_title">职业目标</td>
									<td>
										<textarea id="careergoalsid" name="careergoals"
											style="height: 90px; width: 100%;">${resumeappraisal.careergoals}</textarea>
									</td>
								</tr>
								<tr>
									<td colspan="2" style="text-align: center;">
										<button type="button" id="SubmitButtonId" class="btn btn-info">提交</button>
										<span class="alertMsgClass" id="errormessageShowboxId"></span>
									</td>
								</tr>
							</table>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<jsp:include page="../commons/footServer.jsp"></jsp:include>
	<jsp:include page="../commons/foot.jsp"></jsp:include>
</body>

<script type="text/javascript">
	var operatortype="${OPERATE}";
	$(function() {
		if(operatortype=='2'){
			alert('保存成功!');
		}
		//自我评价
		validateInput('appraisalid', function(id, val, obj) {
			if (valid_maxLength(val, 256)) {
				return {
					valid : false,
					msg : '长度不能大于' + 256
				};
			}
			return {
				valid : true,
				msg : '正确'
			};
		});
		//职业目标
		validateInput('careergoalsid', function(id, val, obj) {
			if (valid_maxLength(val, 256)) {
				return {
					valid : false,
					msg : '长度不能大于' + 256
				};
			}
			return {
				valid : true,
				msg : '正确'
			};
		});
		
		$('#SubmitButtonId')
				.bind(
						'click',
						function() {
							if (!validate('SubmitFormId')) {
								$('#errormessageShowboxId').text('信息录入有误，请检查！');
							} else {
								if (confirm("是否提交数据?")) {
									$('#SubmitFormId').submit();
									$('#SubmitButtonId').hide();
									$('#SubmitButtonId')
											.before(
													"<h2><span class='label label-info glyphicon glyphicon-link'>提交中...</span></h2>");
								}
							}
						});
	});
</script>

</html>

src/wcp-web/src/main/webapp/view/web-simple/resume/educate.jsp
<%@ page language="java" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib uri="/view/conf/farmtag.tld" prefix="PF"%>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<base href="<PF:basePath/>" />
<title>${USEROBJ.name}-教育经历-<PF:ParameterValue
		key="config.sys.title" /></title>
<meta name="description"
	content='<PF:ParameterValue key="config.sys.mate.description"/>'>
<meta name="keywords"
	content='<PF:ParameterValue key="config.sys.mate.keywords"/>'>
<meta name="author"
	content='<PF:ParameterValue key="config.sys.mate.author"/>'>
<meta name="robots" content="noindex,nofllow">
<jsp:include page="../atext/include-web.jsp"></jsp:include>
<script charset="utf-8"
	src="<PF:basePath/>text/lib/super-validate/validate.js"></script>
<script charset="utf-8"
	src="<PF:basePath/>text/lib/bootstrapdatepicker/bootstrap-datetimepicker.min.js"></script>
<link
	href="<PF:basePath/>text/lib/bootstrapdatepicker/bootstrap-datetimepicker.css"
	rel="stylesheet">
<link href="view/web-simple/atext/style/resume.css" rel="stylesheet">
</head>
<body>
	<jsp:include page="../commons/head.jsp"></jsp:include>
	<jsp:include page="../commons/superContent.jsp"></jsp:include>
	<div class="containerbox">
		<div class="container ">
			<div class="row  column_box">
				<div class="col-md-12">
					<h3>${USEROBJ.name}-教育经历<a
							class="resum_button btn btn-info btn-sm"
							href="resume/view.do?userid=${USEROBJ.id}">返回</a><a
							class="resum_button btn btn-info btn-sm"
							href="resume/educateEdit.do?userid=${USEROBJ.id}&pagetype=1">新增</a>
					</h3>
				</div>
			</div>
			<div class="row ">
				<div class="widget-box shadow-box" style="min-width: 800px;">
					<div class="title">
						<h3>
							<i class="glyphicon glyphicon-star"></i>教育经历
						</h3>
					</div>
					<div class="stream-list p-stream">
						<table class="table">
							<thead>
								<tr>
									<th>#</th>
									<th style="width: 100px;">学历/学位</th>
									<th>就读时间</th>
									<th style="width: 100px;">是否统招</th>
									<th>学校名称</th>
									<th>专业名称</th>
									<!-- <th>备注</th> -->
									<th style="width: 200px; text-align: right;">操作</th>
								</tr>
							</thead>
							<tbody>
								<c:forEach items="${educates}" var="none">
									<tr>
										<td></td>
										<td>${none.degree}</td>
										<td>${none.datetime}至${none.dateend}</td>
										<td>${none.unitaryis}</td>
										<td>${none.schoolname}</td>
										<td>${none.specialityname}</td>
										<!-- <td>${none.pcontent}</td> -->
										<td><a class="resum_button btn btn-info btn-xs"
											href="resume/educateEdit.do?userid=${USEROBJ.id }&educateid=${none.id}&pagetype=2">编辑</a><a
											class="resum_button btn btn-info btn-xs delbutton"
											para="userid=${USEROBJ.id }&educateid=${none.id}&pagetype=3">删除</a></td>
									</tr>
								</c:forEach>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<c:if test="${pagetype=='1'||pagetype=='2'}">
				<div class="row ">
					<div class="widget-box shadow-box" style="min-width: 800px;">
						<div class="stream-list p-stream">
							<form role="form" action="resume/educateCommit.do"
								id="SubmitFormId" method="post">
								<input type="hidden" name="id" value="${educate.id}">
								<table class="table resum_unit" style="font-size: 12px;">
									<tr>
										<td class="resum_title">学历/学位<span class="alertMsgClass">*</span></td>
										<td style="width: 25%"><select class="form-control"
											name="degree" id="degreeid" val="${educate.degree}">
												<option value=""></option>
												<PF:OptionDictionary index="RESUME_DEGREE" isTextValue="0" />
										</select></td>
										<td class="resum_title"></td>
										<td style="width: 25%"></td>
										<td class="resum_title"></td>
										<td></td>
									</tr>
									<tr>
										<td class="resum_title">就读时间<span class="alertMsgClass">*</span></td>
										<td><div class="input-group ">
												<div class="input-group-addon">
													<span class="glyphicon glyphicon-calendar"
														aria-hidden="true"></span>
												</div>
												<input type="text" class="form-control form_day"
													name="datetime" id="datetimeid" value="${educate.datetime}">
												<div class="input-group-addon">至</div>
												<div class="input-group-addon">
													<span class="glyphicon glyphicon-calendar"
														aria-hidden="true"></span>
												</div>
												<input type="text" class="form-control form_day"
													name="dateend" id="dateendid" value="${educate.dateend}">
											</div>
											<div id="dateendMsgId"></div>
										</td>
										<td class="resum_title">是否统招<span class="alertMsgClass">*</span></td>
										<td><select class="form-control" name="unitaryis"
											id="unitaryisid" val="${educate.unitaryis}">
												<option value=""></option>
												<PF:OptionDictionary index="RESUME_UNITARYIS"
													isTextValue="0" />
										</select></td>
										<td class="resum_title"></td>
										<td></td>
									</tr>
									<tr>
										<td class="resum_title">学校名称<span class="alertMsgClass">*</span></td>
										<td><input type="text" class="form-control form_year"
											name="schoolname" id="schoolnameid"
											value="${educate.schoolname}"></td>
										<td class="resum_title">专业名称<span class="alertMsgClass">*</span></td>
										<td><input type="text" class="form-control form_year"
											name="specialityname" id="specialitynameid"
											value="${educate.specialityname}"></td>
										<td class="resum_title"></td>
										<td></td>
									</tr>
									<tr>
										<td class="resum_title">备注</td>
										<td colspan="5"><textarea id="pcontentid" name="pcontent"
												style="height: 90px; width: 100%;">${educate.pcontent}</textarea></td>
									</tr>
									<tr>
										<td colspan="6" style="text-align: center;"><button
												type="button" id="SubmitButtonId" class="btn btn-info">提交</button>
											<span class="alertMsgClass" id="errormessageShowboxId"></span></td>
									</tr>
								</table>
							</form>
						</div>
					</div>
				</div>
			</c:if>
		</div>
	</div>
	<jsp:include page="../commons/footServer.jsp"></jsp:include>
	<jsp:include page="../commons/foot.jsp"></jsp:include>
</body>

<script type="text/javascript">
	var operatortype = "${OPERATE}";
	$(function() {
		$('select', '#SubmitFormId').each(function(i, obj) {
			var val = $(obj).attr('val');
			$(obj).val(val);
		});
		$(".form_day").datetimepicker({
			format : "yyyy-mm",
			showMeridian : true,
			autoclose : true,
			todayBtn : true,
			minView : 3,
			startView : 3
		});
		//删除按钮
		$(".delbutton").bind(
				'click',
				function() {
					if (confirm("是否删除该数据?")) {
						window.location = "resume/educateEdit.do?"
								+ $(this).attr('para');
					}
				});
		//学历/学位
		validateInput('degreeid', function(id, val, obj) {
			if (valid_isNull(val)) {
				return {
					valid : false,
					msg : '不能为空'
				};
			}
			return {
				valid : true,
				msg : '正确'
			};
		});
		//就读时间1
		validateInput('datetimeid', function(id, val, obj) {
			if (valid_isNull(val)) {
				return {
					valid : false,
					msg : '不能为空'
				};
			}
			if (valid_maxLength(val, 7)) {
				return {
					valid : false,
					msg : '长度不能大于' + 7
				};
			}
			return {
				valid : true,
				msg : '正确'
			};
		},'dateendMsgId');
		//就读时间2
		validateInput('dateendid', function(id, val, obj) {
			if (valid_isNull(val)) {
				return {
					valid : false,
					msg : '不能为空'
				};
			}
			if (valid_maxLength(val, 7)) {
				return {
					valid : false,
					msg : '长度不能大于' + 7
				};
			}
			return {
				valid : true,
				msg : '正确'
			};
		},'dateendMsgId');
		//是否统招
		validateInput('unitaryisid', function(id, val, obj) {
			if (valid_isNull(val)) {
				return {
					valid : false,
					msg : '不能为空'
				};
			}
			return {
				valid : true,
				msg : '正确'
			};
		});
		//学校名称
		validateInput('schoolnameid', function(id, val, obj) {
			if (valid_isNull(val)) {
				return {
					valid : false,
					msg : '不能为空'
				};
			}
			if (valid_maxLength(val, 32)) {
				return {
					valid : false,
					msg : '长度不能大于' + 32
				};
			}
			return {
				valid : true,
				msg : '正确'
			};
		});
		//专业名称
		validateInput('specialitynameid', function(id, val, obj) {
			if (valid_isNull(val)) {
				return {
					valid : false,
					msg : '不能为空'
				};
			}
			if (valid_maxLength(val, 64)) {
				return {
					valid : false,
					msg : '长度不能大于' + 64
				};
			}
			return {
				valid : true,
				msg : '正确'
			};
		});
		//备注
		validateInput('pcontentid', function(id, val, obj) {
			if (valid_maxLength(val, 128)) {
				return {
					valid : false,
					msg : '长度不能大于' + 128
				};
			}
			return {
				valid : true,
				msg : '正确'
			};
		});
		$('#SubmitButtonId')
				.bind(
						'click',
						function() {
							if (!validate('SubmitFormId')) {
								$('#errormessageShowboxId').text('信息录入有误，请检查！');
							} else {
								if (confirm("是否提交数据?")) {
									$('#SubmitFormId').submit();
									$('#SubmitButtonId').hide();
									$('#SubmitButtonId')
											.before(
													"<h2><span class='label label-info glyphicon glyphicon-link'>提交中...</span></h2>");
								}
							}
						});
	});
</script>

</html>